name: Publish
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to GitHub Packages
      uses: HurricanKai/Publish-Docker-Github-Action@master
      with:
        name: docker.pkg.github.com/chriskolenko/liquibase/liquibase
        username: ${{ secrets.GITHUB_DOCKER_USERNAME }}
        password: ${{ secrets.GITHUB_DOCKER_TOKEN }}
        registry: docker.pkg.github.com
    - name: Publish to Dockerhub
      uses: HurricanKai/Publish-Docker-Github-Action@master
      with:
        name: chriskolenko/liquibase
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Publish to GitHub Packages with tag
      uses: HurricanKai/Publish-Docker-Github-Action@master
      if: contains(github.ref, 'refs/tags/v')
      with:
        name: docker.pkg.github.com/chriskolenko/liquibase/liquibase
        username: ${{ secrets.GITHUB_DOCKER_USERNAME }}
        password: ${{ secrets.GITHUB_DOCKER_TOKEN }}
        registry: docker.pkg.github.com
        tagging: true
    - name: Publish to Dockerhub with tag
      uses: HurricanKai/Publish-Docker-Github-Action@master
      with:
        name: chriskolenko/liquibase
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tagging: true